/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.tmforum.alarm.api;

import com.tmforum.alarm.model.AckAlarmCreateEvent;
import com.tmforum.alarm.model.AckAlarmStateChangeEvent;
import com.tmforum.alarm.model.AlarmAttributeValueChangeEvent;
import com.tmforum.alarm.model.AlarmCreateEvent;
import com.tmforum.alarm.model.AlarmDeleteEvent;
import com.tmforum.alarm.model.AlarmStateChangeEvent;
import com.tmforum.alarm.model.ClearAlarmCreateEvent;
import com.tmforum.alarm.model.ClearAlarmStateChangeEvent;
import com.tmforum.alarm.model.CommentAlarmCreateEvent;
import com.tmforum.alarm.model.CommentAlarmStateChangeEvent;
import com.tmforum.alarm.model.Error;
import com.tmforum.alarm.model.GroupAlarmCreateEvent;
import com.tmforum.alarm.model.GroupAlarmStateChangeEvent;
import com.tmforum.alarm.model.UnAckAlarmCreateEvent;
import com.tmforum.alarm.model.UnAckAlarmStateChangeEvent;
import com.tmforum.alarm.model.UnGroupAlarmCreateEvent;
import com.tmforum.alarm.model.UnGroupAlarmStateChangeEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Validated
@Tag(name = "notification listener", description = "Notifications for Resource Lifecycle and event notifications")
public interface ListenerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /listener/ackAlarmCreateEvent : Client listener for entity AckAlarmCreateEvent
     * Example of a client listener for receiving the notification AckAlarmCreateEvent
     *
     * @param ackAlarmCreateEvent AckAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "ackAlarmCreateEvent",
        summary = "Client listener for entity AckAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification AckAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/ackAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> ackAlarmCreateEvent(
        @Parameter(name = "AckAlarmCreateEvent", description = "AckAlarm create Event payload", required = true) @Valid @RequestBody AckAlarmCreateEvent ackAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/ackAlarmStateChangeEvent : Client listener for entity AckAlarmStateChangeEvent
     * Example of a client listener for receiving the notification AckAlarmStateChangeEvent
     *
     * @param ackAlarmStateChangeEvent AckAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "ackAlarmStateChangeEvent",
        summary = "Client listener for entity AckAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification AckAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/ackAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> ackAlarmStateChangeEvent(
        @Parameter(name = "AckAlarmStateChangeEvent", description = "AckAlarm stateChange Event payload", required = true) @Valid @RequestBody AckAlarmStateChangeEvent ackAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/alarmAttributeValueChangeEvent : Client listener for entity AlarmAttributeValueChangeEvent
     * Example of a client listener for receiving the notification AlarmAttributeValueChangeEvent
     *
     * @param alarmAttributeValueChangeEvent Alarm attributeValueChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "alarmAttributeValueChangeEvent",
        summary = "Client listener for entity AlarmAttributeValueChangeEvent",
        description = "Example of a client listener for receiving the notification AlarmAttributeValueChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/alarmAttributeValueChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> alarmAttributeValueChangeEvent(
        @Parameter(name = "AlarmAttributeValueChangeEvent", description = "Alarm attributeValueChange Event payload", required = true) @Valid @RequestBody AlarmAttributeValueChangeEvent alarmAttributeValueChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/alarmCreateEvent : Client listener for entity AlarmCreateEvent
     * Example of a client listener for receiving the notification AlarmCreateEvent
     *
     * @param alarmCreateEvent Alarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "alarmCreateEvent",
        summary = "Client listener for entity AlarmCreateEvent",
        description = "Example of a client listener for receiving the notification AlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/alarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> alarmCreateEvent(
        @Parameter(name = "AlarmCreateEvent", description = "Alarm create Event payload", required = true) @Valid @RequestBody AlarmCreateEvent alarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/alarmDeleteEvent : Client listener for entity AlarmDeleteEvent
     * Example of a client listener for receiving the notification AlarmDeleteEvent
     *
     * @param alarmDeleteEvent Alarm delete Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "alarmDeleteEvent",
        summary = "Client listener for entity AlarmDeleteEvent",
        description = "Example of a client listener for receiving the notification AlarmDeleteEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/alarmDeleteEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> alarmDeleteEvent(
        @Parameter(name = "AlarmDeleteEvent", description = "Alarm delete Event payload", required = true) @Valid @RequestBody AlarmDeleteEvent alarmDeleteEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/alarmStateChangeEvent : Client listener for entity AlarmStateChangeEvent
     * Example of a client listener for receiving the notification AlarmStateChangeEvent
     *
     * @param alarmStateChangeEvent Alarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "alarmStateChangeEvent",
        summary = "Client listener for entity AlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification AlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/alarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> alarmStateChangeEvent(
        @Parameter(name = "AlarmStateChangeEvent", description = "Alarm stateChange Event payload", required = true) @Valid @RequestBody AlarmStateChangeEvent alarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/clearAlarmCreateEvent : Client listener for entity ClearAlarmCreateEvent
     * Example of a client listener for receiving the notification ClearAlarmCreateEvent
     *
     * @param clearAlarmCreateEvent ClearAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "clearAlarmCreateEvent",
        summary = "Client listener for entity ClearAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification ClearAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/clearAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> clearAlarmCreateEvent(
        @Parameter(name = "ClearAlarmCreateEvent", description = "ClearAlarm create Event payload", required = true) @Valid @RequestBody ClearAlarmCreateEvent clearAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/clearAlarmStateChangeEvent : Client listener for entity ClearAlarmStateChangeEvent
     * Example of a client listener for receiving the notification ClearAlarmStateChangeEvent
     *
     * @param clearAlarmStateChangeEvent ClearAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "clearAlarmStateChangeEvent",
        summary = "Client listener for entity ClearAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification ClearAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/clearAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> clearAlarmStateChangeEvent(
        @Parameter(name = "ClearAlarmStateChangeEvent", description = "ClearAlarm stateChange Event payload", required = true) @Valid @RequestBody ClearAlarmStateChangeEvent clearAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/commentAlarmCreateEvent : Client listener for entity CommentAlarmCreateEvent
     * Example of a client listener for receiving the notification CommentAlarmCreateEvent
     *
     * @param commentAlarmCreateEvent CommentAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "commentAlarmCreateEvent",
        summary = "Client listener for entity CommentAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification CommentAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/commentAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> commentAlarmCreateEvent(
        @Parameter(name = "CommentAlarmCreateEvent", description = "CommentAlarm create Event payload", required = true) @Valid @RequestBody CommentAlarmCreateEvent commentAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/commentAlarmStateChangeEvent : Client listener for entity CommentAlarmStateChangeEvent
     * Example of a client listener for receiving the notification CommentAlarmStateChangeEvent
     *
     * @param commentAlarmStateChangeEvent CommentAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "commentAlarmStateChangeEvent",
        summary = "Client listener for entity CommentAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification CommentAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/commentAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> commentAlarmStateChangeEvent(
        @Parameter(name = "CommentAlarmStateChangeEvent", description = "CommentAlarm stateChange Event payload", required = true) @Valid @RequestBody CommentAlarmStateChangeEvent commentAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/groupAlarmCreateEvent : Client listener for entity GroupAlarmCreateEvent
     * Example of a client listener for receiving the notification GroupAlarmCreateEvent
     *
     * @param groupAlarmCreateEvent GroupAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "groupAlarmCreateEvent",
        summary = "Client listener for entity GroupAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification GroupAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/groupAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> groupAlarmCreateEvent(
        @Parameter(name = "GroupAlarmCreateEvent", description = "GroupAlarm create Event payload", required = true) @Valid @RequestBody GroupAlarmCreateEvent groupAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/groupAlarmStateChangeEvent : Client listener for entity GroupAlarmStateChangeEvent
     * Example of a client listener for receiving the notification GroupAlarmStateChangeEvent
     *
     * @param groupAlarmStateChangeEvent GroupAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "groupAlarmStateChangeEvent",
        summary = "Client listener for entity GroupAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification GroupAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/groupAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> groupAlarmStateChangeEvent(
        @Parameter(name = "GroupAlarmStateChangeEvent", description = "GroupAlarm stateChange Event payload", required = true) @Valid @RequestBody GroupAlarmStateChangeEvent groupAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/unAckAlarmCreateEvent : Client listener for entity UnAckAlarmCreateEvent
     * Example of a client listener for receiving the notification UnAckAlarmCreateEvent
     *
     * @param unAckAlarmCreateEvent UnAckAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "unAckAlarmCreateEvent",
        summary = "Client listener for entity UnAckAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification UnAckAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/unAckAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> unAckAlarmCreateEvent(
        @Parameter(name = "UnAckAlarmCreateEvent", description = "UnAckAlarm create Event payload", required = true) @Valid @RequestBody UnAckAlarmCreateEvent unAckAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/unAckAlarmStateChangeEvent : Client listener for entity UnAckAlarmStateChangeEvent
     * Example of a client listener for receiving the notification UnAckAlarmStateChangeEvent
     *
     * @param unAckAlarmStateChangeEvent UnAckAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "unAckAlarmStateChangeEvent",
        summary = "Client listener for entity UnAckAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification UnAckAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/unAckAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> unAckAlarmStateChangeEvent(
        @Parameter(name = "UnAckAlarmStateChangeEvent", description = "UnAckAlarm stateChange Event payload", required = true) @Valid @RequestBody UnAckAlarmStateChangeEvent unAckAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/unGroupAlarmCreateEvent : Client listener for entity UnGroupAlarmCreateEvent
     * Example of a client listener for receiving the notification UnGroupAlarmCreateEvent
     *
     * @param unGroupAlarmCreateEvent UnGroupAlarm create Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "unGroupAlarmCreateEvent",
        summary = "Client listener for entity UnGroupAlarmCreateEvent",
        description = "Example of a client listener for receiving the notification UnGroupAlarmCreateEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/unGroupAlarmCreateEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> unGroupAlarmCreateEvent(
        @Parameter(name = "UnGroupAlarmCreateEvent", description = "UnGroupAlarm create Event payload", required = true) @Valid @RequestBody UnGroupAlarmCreateEvent unGroupAlarmCreateEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /listener/unGroupAlarmStateChangeEvent : Client listener for entity UnGroupAlarmStateChangeEvent
     * Example of a client listener for receiving the notification UnGroupAlarmStateChangeEvent
     *
     * @param unGroupAlarmStateChangeEvent UnGroupAlarm stateChange Event payload (required)
     * @return Notified (status code 204)
     *         or Error (status code 200)
     */
    @Operation(
        operationId = "unGroupAlarmStateChangeEvent",
        summary = "Client listener for entity UnGroupAlarmStateChangeEvent",
        description = "Example of a client listener for receiving the notification UnGroupAlarmStateChangeEvent",
        tags = { "notification listener" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notified"),
            @ApiResponse(responseCode = "default", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/listener/unGroupAlarmStateChangeEvent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> unGroupAlarmStateChangeEvent(
        @Parameter(name = "UnGroupAlarmStateChangeEvent", description = "UnGroupAlarm stateChange Event payload", required = true) @Valid @RequestBody UnGroupAlarmStateChangeEvent unGroupAlarmStateChangeEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"@schemaLocation\" : \"@schemaLocation\", \"message\" : \"message\", \"referenceError\" : \"referenceError\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
