package io.tmf.alarm.common.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import io.tmf.alarm.common.model.Alarm;
import io.tmf.alarm.common.model.AlarmRef;
import io.tmf.alarm.common.model.AlarmType;
import com.tmforum.alarm.model.AlarmedObjectRef;
import com.tmforum.alarm.model.Comment;
import com.tmforum.alarm.model.CrossedThresholdInformation;
import com.tmforum.alarm.model.PerceivedSeverity;
import com.tmforum.alarm.model.RelatedPlace;
import com.tmforum.alarm.model.ServiceRef;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Alarm.class, name = "Alarm"),
  @JsonSubTypes.Type(value = AlarmRef.class, name = "AlarmRef")
})


public interface AlarmRefOrValue {
    public String getAtType();
}
